name: CI quality (extended)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
permissions:
  contents: read

jobs:
  cmake:
    name: cmake / PRESET=${{ matrix.preset }} / VARIANT=${{ matrix.variant }} / LOCALCLIENT=${{ matrix.localclient }} / COMPILER=${{ matrix.compiler }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - preset: default
            variant: all
            localclient: OFF
            compiler: gcc
          - preset: gnuinstall
            variant: server
            localclient: OFF
            compiler: clang
          - preset: packaging
            variant: client
            localclient: ON
            compiler: gcc
          - preset: default
            variant: client
            localclient: OFF
            compiler: clang
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-env-debian
        with:
          profile: debian

      - uses: ./.github/actions/select-compiler
        with:
          compiler: ${{ matrix.compiler }}

      - name: Configure (CMake)
        run: |
          cmake --preset ${{ matrix.preset }} \
            -DENABLE_SSL=ON \
            -DENABLE_LDAP=ON \
            -DXYMON_VARIANT=${{ matrix.variant }} \
            -DLOCALCLIENT=${{ matrix.localclient }}

      - name: Build (CMake)
        run: |
          cmake --build --preset ${{ matrix.preset }} --parallel 1

  bsd:
    name: BSD ${{ matrix.variant }} / OS=${{ matrix.os.name }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: freebsd
            architecture: x86-64
            version: "15.0"
          - name: openbsd
            architecture: x86-64
            version: "7.8"
          - name: netbsd
            architecture: x86-64
            version: "10.1"
        variant: [server, client]
    steps:
      - uses: actions/checkout@v4
      - name: build ${{ matrix.os.name }} (${{ matrix.variant }})
        uses: cross-platform-actions/action@v0.32.0
        with:
          operating_system: ${{ matrix.os.name }}
          architecture: ${{ matrix.os.architecture }}
          version: ${{ matrix.os.version }}
          shell: bash
          memory: 512M
          cpu_count: 1
          run: |
            export VARIANT="${{ matrix.variant }}"
            bash scripts/ci/bsd-build.sh
