name: CI quality (extended)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
permissions:
  contents: read

jobs:
  cmake:
    name: cmake / PRESET=${{ matrix.preset }} / VARIANT=${{ matrix.variant }} / LOCALCLIENT=${{ matrix.localclient }} / COMPILER=${{ matrix.compiler }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - preset: default
            variant: all
            localclient: OFF
            compiler: gcc
          - preset: gnuinstall
            variant: server
            localclient: OFF
            compiler: clang
          - preset: packaging
            variant: client
            localclient: ON
            compiler: gcc
          - preset: default
            variant: client
            localclient: OFF
            compiler: clang
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-env
        with:
          profile: debian

      - uses: ./.github/actions/select-compiler
        with:
          compiler: ${{ matrix.compiler }}

      - name: Configure (CMake)
        run: |
          cmake --preset ${{ matrix.preset }} \
            -DENABLE_SSL=ON \
            -DENABLE_LDAP=ON \
            -DXYMON_VARIANT=${{ matrix.variant }} \
            -DLOCALCLIENT=${{ matrix.localclient }}

      - name: Build (CMake)
        run: |
          cmake --build --preset ${{ matrix.preset }} --parallel 1
