name: CI quality (extended)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        variant: [server, client]
        compiler: [gcc, clang]
        profile: [default, debian]

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-env
        with:
          profile: ${{ matrix.profile }}

      - uses: ./.github/actions/select-compiler
        with:
          compiler: ${{ matrix.compiler }}

      - uses: ./.github/actions/configure-xymon
        with:
          variant: ${{ matrix.variant }}
          profile: ${{ matrix.profile }}

      - uses: ./.github/actions/build-xymon

  cmake:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - preset: default
            variant: server
            localclient: OFF
            name: server
          - preset: gnuinstall
            variant: server
            localclient: OFF
            name: server
          - preset: default
            variant: client
            localclient: ON
            name: client CT=client
          - preset: gnuinstall
            variant: client
            localclient: ON
            name: client CT=client
          - preset: default
            variant: client
            localclient: OFF
            name: client CT=server
          - preset: gnuinstall
            variant: client
            localclient: OFF
            name: client CT=server
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-env
        with:
          profile: debian

      - uses: ./.github/actions/select-compiler
        with:
          compiler: gcc

      - name: Configure (CMake)
        run: |
          cmake --preset ${{ matrix.preset }} \
            -DENABLE_SSL=ON \
            -DENABLE_LDAP=ON \
            -DXYMON_VARIANT=${{ matrix.variant }} \
            -DLOCALCLIENT=${{ matrix.localclient }}

      - name: Build (CMake)
        run: |
          cmake --build --preset ${{ matrix.preset }} --parallel 1
