name: CI validation (Linux)

on:
  workflow_dispatch:
  pull_request:
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        include:
          - name: server
            variant: server
          - name: client CT=client
            variant: client
            conftype: client
          - name: client CT=server
            variant: client
            conftype: server

    steps:
      - uses: actions/checkout@v4

      - name: Setup (Debian)
        env:
          ENABLE_LDAP: ON
          XYMON_VARIANT: ${{ matrix.variant }}
        run: |
          bash scripts/ci/setup-debian.sh default

      - uses: ./.github/actions/select-compiler
        with:
          compiler: gcc

      - uses: ./.github/actions/configure-xymon
        with:
          variant: ${{ matrix.variant }}
          profile: default
        env:
          CONFTYPE: ${{ matrix.conftype }}

      - uses: ./.github/actions/build-xymon

  cmake:
    name: cmake / PRESET=${{ matrix.preset }} / VARIANT=server / LOCALCLIENT=OFF / COMPILER=gcc
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        preset: [default, gnuinstall]
    steps:
      - uses: actions/checkout@v4

      - name: Setup (Debian)
        env:
          ENABLE_LDAP: ON
          XYMON_VARIANT: server
        run: |
          bash scripts/ci/setup-debian.sh debian

      - uses: ./.github/actions/select-compiler
        with:
          compiler: gcc

      - name: Configure (CMake)
        env:
          PRESET: ${{ matrix.preset }}
          ENABLE_SSL: ON
          ENABLE_LDAP: ON
          XYMON_VARIANT: server
          LOCALCLIENT: OFF
        run: |
          bash scripts/ci/cmake-configure.sh

      - name: Build (CMake)
        env:
          PRESET: ${{ matrix.preset }}
        run: |
          bash scripts/ci/cmake-build.sh
