name: CI validation (Linux)

on:
  workflow_dispatch:
  pull_request:
  workflow_call:
permissions:
  contents: read

jobs:
  debian_legacy:
    name: debian_legacy / VARIANT=${{ matrix.name }} / COMPILER=${{ matrix.compiler }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: server
            variant: server
            compiler: gcc
            conftype: server
          - name: client CT=client
            variant: client
            compiler: gcc
            conftype: client
          - name: client CT=server
            variant: client
            compiler: gcc
            conftype: server

    steps:
      - uses: actions/checkout@v4

      - name: Setup (Debian)
        env:
          ENABLE_LDAP: ON
          XYMON_VARIANT: ${{ matrix.variant }}
        run: |
          bash scripts/ci/setup-linux-debian.sh debian

      - name: Setup (Compiler)
        run: |
          bash scripts/ci/setup-compiler.sh ${{ matrix.compiler }}

      - name: Configure (Legacy)
        env:
          CONFTYPE: ${{ matrix.conftype }}
          ENABLESSL: ${{ matrix.variant == 'client' && 'n' || 'y' }}
        run: |
          bash scripts/ci/legacy-configure.sh ${{ matrix.variant }} debian

      - name: Build (Legacy)
        run: |
          bash scripts/ci/legacy-build.sh

  debian_cmake:
    name: debian_cmake / PRESET=${{ matrix.preset }} / VARIANT=server / COMPILER=gcc
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        preset: [default, gnuinstall]
    steps:
      - uses: actions/checkout@v4

      - name: Setup (Debian)
        env:
          ENABLE_LDAP: ON
          XYMON_VARIANT: server
        run: |
          bash scripts/ci/setup-linux-debian.sh debian

      - name: Setup (Compiler)
        run: |
          bash scripts/ci/setup-compiler.sh gcc

      - name: Configure (CMake)
        env:
          PRESET: ${{ matrix.preset }}
          ENABLE_SSL: ON
          ENABLE_LDAP: ON
          XYMON_VARIANT: server
        run: |
          bash scripts/ci/cmake-configure.sh

      - name: Build (CMake)
        env:
          PRESET: ${{ matrix.preset }}
        run: |
          bash scripts/ci/cmake-build.sh
