name: CI validation (Linux)

on:
  workflow_dispatch:
  pull_request:
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        include:
          - name: server
            variant: server
          - name: client CT=client
            variant: client
            conftype: client
          - name: client CT=server
            variant: client
            conftype: server

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-env
        with:
          profile: default

      - uses: ./.github/actions/select-compiler
        with:
          compiler: gcc

      - uses: ./.github/actions/configure-xymon
        with:
          variant: ${{ matrix.variant }}
          profile: default
        env:
          CONFTYPE: ${{ matrix.conftype }}

      - uses: ./.github/actions/build-xymon

  cmake:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        preset: [default, gnuinstall, packaging]
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-env
        with:
          profile: debian

      - uses: ./.github/actions/select-compiler
        with:
          compiler: gcc

      - name: Configure (CMake)
        run: |
          cmake --preset ${{ matrix.preset }} \
            -DENABLE_SSL=ON \
            -DENABLE_LDAP=ON \
            -DXYMON_VARIANT=server \
            -DLOCALCLIENT=OFF

      - name: Build (CMake)
        run: |
          cmake --build --preset ${{ matrix.preset }} --parallel 1
