name: ref_make_linux

on:
  workflow_dispatch:

jobs:
  ref-make-linux:
    name: ref_make_linux (${{ matrix.name }})
    env:
      BUILD_TOOL: make
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: server
            variant: server
          - name: client ct-client
            variant: localclient
          - name: client ct-server
            variant: client

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate legacy references
        run: |
          uname -a || true
          gcc --version || true
          ld --version || true
          build_tool="${BUILD_TOOL}"
          bash ci/bootstrap-install-and-refs.sh \
            --os linux \
            --variant "${{ matrix.variant }}" \
            --build "$build_tool"
      - name: Upload legacy references
        uses: actions/upload-artifact@v4
        with:
          name: ref_${{ env.BUILD_TOOL }}_linux-${{ matrix.variant }}
          path: |
            docs/refs/${{ env.BUILD_TOOL }}.linux.${{ matrix.variant }}.*
          if-no-files-found: error
