name: ref_make_netbsd

on:
  workflow_dispatch:

jobs:
  ref-make-netbsd:
    name: ref_make_netbsd (${{ matrix.name }})
    env:
      BUILD_TOOL: make
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: server
            variant: server
          - name: client ct-client
            variant: localclient
          - name: client ct-server
            variant: client

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate legacy references
        uses: cross-platform-actions/action@v0.32.0
        with:
          operating_system: netbsd
          architecture: x86-64
          version: "10.1"
          shell: bash
          memory: 1024M
          cpu_count: 2
          run: |
            uname -a || true
            gcc --version || true
            ld --version || true
          build_tool="${BUILD_TOOL}"
          bash ci/bootstrap-install-and-refs.sh \
            --os netbsd \
            --version "10.1" \
            --variant "${{ matrix.variant }}" \
            --build "$build_tool"
          sync_files: true
          shutdown_vm: true

      - name: Upload legacy references
        uses: actions/upload-artifact@v4
        with:
          name: ref_${{ env.BUILD_TOOL }}_netbsd-${{ matrix.variant }}
          path: |
            docs/refs/make.netbsd.${{ matrix.variant }}.*
          if-no-files-found: error
