name: Xymon build (Linux)

on:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build:
    name: build (${{ matrix.name }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: server
            variant: server

          - name: client CT=client
            variant: client
            conftype: client

          - name: client CT=server
            variant: client
            conftype: server

    steps:
      - uses: actions/checkout@v4

      - name: Setup (Debian)
        env:
          ENABLE_LDAP: ON
          XYMON_VARIANT: ${{ matrix.variant }}
        run: |
          bash scripts/ci/setup-debian.sh debian

      - uses: ./.github/actions/select-compiler
        with:
          compiler: gcc

      - uses: ./.github/actions/configure-xymon
        with:
          variant: ${{ matrix.variant }}
          profile: debian
        env:
          CONFTYPE: ${{ matrix.conftype }}

      - uses: ./.github/actions/build-xymon
