name: Xymon build (Linux)

on:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build:
    name: build (${{ matrix.name }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: server
            variant: server

          - name: client CT=client
            variant: client
            conftype: client

          - name: client CT=server
            variant: client
            conftype: server

    steps:
      - uses: actions/checkout@v4

      - name: Setup (Debian)
        env:
          CI: 1
          ENABLE_LDAP: ON
          XYMON_VARIANT: ${{ matrix.variant }}
        run: |
          bash scripts/ci/setup-linux-debian.sh debian

      - name: Setup compiler
        run: |
          bash scripts/ci/setup-compiler.sh gcc

      - name: Configure (Autotools)
        env:
          CI: 1
          CONFTYPE: ${{ matrix.conftype }}
        run: |
          bash scripts/ci/legacy-configure.sh ${{ matrix.variant }} debian

      - name: Build (Autotools)
        env:
          CI: 1
        run: |
          bash scripts/ci/legacy-build.sh
